# Generated by Django 3.2.4 on 2021-11-28 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_panel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Students_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamClearanceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('cleared', 'cleared'), ('pending', 'pending'), ('rejected', 'rejected')], max_length=20)),
                ('semesterInfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semester_info', to='Admin_panel.semester')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_clearance', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
